export type Job={id:string;title:string;category:string;department:string;location:string;employmentType:string;skills:string[];description:string;openings?:number;customQuestions?:string[];isOpen:boolean};
export const categories=["Cybersecurity","Marketing","Quality Assurance","Product Management","Data","Social Media","AI Web","Design","AI Graphics","Web Development","App Development","Explore All Roles"];
export const jobs:Job[]=[
	{id:"frontend-dev",title:"Frontend Developer",category:"Web Development",department:"Engineering",location:"Remote, US",employmentType:"Internship",skills:["React","TypeScript","Tailwind"],description:"Build polished product UI.",isOpen:true},
	{id:"uiux-designer",title:"UI/UX Designer",category:"Design",department:"Design",location:"Remote, US",employmentType:"Internship",skills:["Figma","User Research","Prototyping"],description:"Design user interfaces and experiences for LocalSM's hiring and marketplace products.",isOpen:true},
	{id:"cyber-intern",title:"Cybersecurity Intern",category:"Cybersecurity",department:"Security",location:"Remote, US",employmentType:"Internship",skills:["Network Security","Problem Solving","Curiosity"],description:"Support our security team with monitoring, threat research, and defensive tooling.",isOpen:true},
	{id:"marketing-intern",title:"On-Site Marketing Intern",category:"Marketing",department:"Marketing",location:"Jabalpur, IN",employmentType:"Internship",skills:["Social Media","Copywriting","Creativity"],description:"Help create campaigns, content, and community outreach for LocalSM.",isOpen:true},
	{id:"qa-intern",title:"Quality Assurance Intern",category:"Quality Assurance",department:"Quality",location:"Remote, US",employmentType:"Internship",skills:["Testing","Attention to Detail","Communication"],description:"Work with the product team to validate features and improve quality.",isOpen:true},
	{id:"pm-intern",title:"Product Management Intern",category:"Product Management",department:"Product",location:"Remote, US",employmentType:"Internship",skills:["Research","Collaboration","Organization"],description:"Support product planning, user research, and roadmap work across local services.",isOpen:true},
	{id:"data-analyst-intern",title:"Data Analyst Intern",category:"Data",department:"Data",location:"Remote, US",employmentType:"Internship",skills:["Excel","SQL","Curiosity"],description:"Analyze marketplace metrics and help turn data into actionable recommendations.",isOpen:true},
	{id:"social-media-intern",title:"Junior Social Media Management Intern",category:"Social Media",department:"Marketing",location:"Remote, US",employmentType:"Internship",skills:["Content Creation","Community","Analytics"],description:"Manage LocalSM social channels and help grow engagement across platforms.",isOpen:true},
	{id:"ai-web-dev-intern",title:"AI Web Developer Intern",category:"AI Web",department:"Engineering",location:"Remote, US",employmentType:"Internship",skills:["JavaScript","AI","Web Development"],description:"Build AI-powered web experiences and prototypes for our local marketplace.",isOpen:true},
	{id:"ai-graphics-designer",title:"AI Graphics Designer",category:"AI Graphics",department:"Design",location:"Remote, US",employmentType:"Internship",skills:["Illustration","AI Tools","Visual Design"],description:"Create on-brand graphics and AI-enhanced creative assets for campaigns.",isOpen:true},
	{id:"flutter-dev",title:"Flutter Developer",category:"App Development",department:"Mobile",location:"Austin, TX",employmentType:"Internship",skills:["Flutter","Dart","Firebase"],description:"Craft cross-platform apps.",isOpen:true}
];
